item_objects = [
{type= 'Point', x= 0, y= 100},
{type= 'Point', x= 50, y= 100},
{type= 'Point', x= 100, y= 100},
{type= 'Point', x= 150, y= 100},
{type= 'Point', x= 200, y= 100},
{type= 'Point', x= 250, y= 100},
{type= 'Point', x= 300, y= 150},
{type= 'Point', x= 350, y= 200},
{type= 'Point', x= 400, y= 250},
{type= 'Point', x= 450, y= 200},
{type= 'Point', x= 500, y= 150},
{type= 'Point', x= 550, y= 100},
{type= 'Point', x= 600, y= 100},
{type= 'Point', x= 650, y= 100},
{type= 'Point', x= 700, y= 100},
{type= 'Point', x= 750, y= 100},
{type= 'Point', x= 800, y= 150},
{type= 'Point', x= 850, y= 200},
{type= 'Point', x= 900, y= 250},
{type= 'Point', x= 950, y= 300},
{type= 'Point', x= 1000, y= 350},
{type= 'Point', x= 1050, y= 300},
{type= 'Point', x= 1100, y= 250},
{type= 'Point', x= 1150, y= 200},
{type= 'Point', x= 1200, y= 150},
{type= 'Point', x= 1250, y= 100},
{type= 'Point', x= 1300, y= 100},
{type= 'Point', x= 1350, y= 100},
{type= 'Point', x= 1400, y= 100},
{type= 'Point', x= 1450, y= 100},
{type= 'Point', x= 1500, y= 100},
{type= 'Point', x= 1550, y= 100},
{type= 'Point', x= 1600, y= 100},
{type= 'Point', x= 1650, y= 100},
{type= 'Point', x= 1700, y= 100},
{type= 'Point', x= 1750, y= 100},
{type= 'Point', x= 1800, y= 100},
{type= 'Point', x= 1850, y= 100},
{type= 'Point', x= 1900, y= 100},
{type= 'Point', x= 1950, y= 100},
{type= 'Point', x= 2000, y= 100},
{type= 'Point', x= 2050, y= 150},
{type= 'Point', x= 2100, y= 200},
{type= 'Coin', x= 2150, y= 250},
{type= 'Point', x= 2200, y= 200},
{type= 'Point', x= 2250, y= 150},
{type= 'Point', x= 2300, y= 100},
{type= 'Point', x= 2350, y= 100},
{type= 'Point', x= 2400, y= 150},
{type= 'Point', x= 2450, y= 200},
{type= 'Coin', x= 2500, y= 250},
{type= 'Point', x= 2550, y= 200},
{type= 'Point', x= 2600, y= 150},
{type= 'Point', x= 2650, y= 100},
{type= 'Point', x= 2700, y= 100},
{type= 'Point', x= 2750, y= 150},
{type= 'Point', x= 2800, y= 200},
{type= 'Coin', x= 2850, y= 250},
{type= 'Point', x= 2900, y= 200},
{type= 'Point', x= 2950, y= 150},
{type= 'Point', x= 3000, y= 100},
{type= 'Point', x= 3050, y= 100},
{type= 'Point', x= 3100, y= 150},
{type= 'Point', x= 3150, y= 200},
{type= 'Coin', x= 3200, y= 250},
{type= 'Point', x= 3250, y= 200},
{type= 'Point', x= 3300, y= 150},
{type= 'Point', x= 3350, y= 100},
{type= 'Point', x= 3400, y= 100},
{type= 'Point', x= 3450, y= 150},
{type= 'Point', x= 3500, y= 200},
{type= 'Coin', x= 3550, y= 250},
{type= 'Point', x= 3600, y= 200},
{type= 'Point', x= 3650, y= 150},
{type= 'Point', x= 3700, y= 100},
{type= 'Point', x= 3750, y= 100},
{type= 'Point', x= 3800, y= 100},
{type= 'Point', x= 3850, y= 100},
{type= 'Point', x= 3900, y= 100},
{type= 'Point', x= 3950, y= 100},
{type= 'Point', x= 4000, y= 100},
{type= 'Point', x= 4050, y= 100},
{type= 'Point', x= 4100, y= 100},
{type= 'Point', x= 4150, y= 100},
{type= 'Point', x= 4200, y= 100},
{type= 'Point', x= 4250, y= 100},
{type= 'Point', x= 4300, y= 100},
{type= 'Point', x= 4350, y= 100},
{type= 'Point', x= 4400, y= 100},
{type= 'Point', x= 4450, y= 100},
{type= 'Point', x= 4500, y= 100},
{type= 'Point', x= 4550, y= 100},
{type= 'Point', x= 4600, y= 100},
{type= 'Point', x= 4650, y= 100},
{type= 'Point', x= 4700, y= 100},
{type= 'Point', x= 4750, y= 100},
{type= 'Point', x= 4800, y= 100},
{type= 'Point', x= 4850, y= 100},
{type= 'Point', x= 4900, y= 100},
{type= 'Point', x= 4950, y= 100},
]
