tile_objects = [
    {type= 2, x= -1440, y= -50},
    {type= 2, x= -1344, y= -50},
    {type= 2, x= -1248, y= -50},
    {type= 2, x= -1152, y= -50},
    {type= 2, x= -1056, y= -50},
    {type= 2, x= -960, y= -50},
    {type= 2, x= -864, y= -50},
    {type= 2, x= -768, y= -50},
    {type= 2, x= -672, y= -50},
    {type= 2, x= -576, y= -50},
    {type= 2, x= -480, y= -50},
    {type= 2, x= -384, y= -50},
    {type= 2, x= -288, y= -50},
    {type= 2, x= -192, y= -50},
    {type= 2, x= -96, y= -50},

    {type= 2, x= 0, y= -50},
    {type= 2, x= 96, y= -50},
    {type= 2, x= 192, y= -50},
    {type= 2, x= 288, y= -50},
    {type= 2, x= 384, y= -50},
    {type= 2, x= 480, y= -50},
    {type= 2, x= 576, y= -50},
    {type= 2, x= 672, y= -50},
    {type= 2, x= 768, y= -50},
    {type= 2, x= 864, y= -50},
    {type= 2, x= 960, y= -50},
    {type= 2, x= 1056, y= -50},
    {type= 2, x= 1152, y= -50},
    {type= 2, x= 1248, y= -50},
    {type= 2, x= 1344, y= -50},
    {type= 2, x= 1440, y= -50},
    {type= 2, x= 1536, y= -50},
    {type= 2, x= 1632, y= -50},
    {type= 2, x= 1728, y= -50},
    {type= 2, x= 1824, y= -50},
    {type= 2, x= 1920, y= -50},
    {type= 3, x= 2016, y= -50},
    {type= 'None', x= 2112, y= -50},
    {type= 'None', x= 2208, y= -50},
    {type= 0, x= 2260, y= -50},

    {type= 'None', x= 2400, y= -50},
    {type= 'None', x= 2496, y= -50},
    {type= 0, x= 2592, y= -50},

    {type= 'None', x= 2688, y= -50},
    {type= 'None', x= 2784, y= -50},
    {type= 0, x= 2950, y= -50},
    {type= 'None', x= 2976, y= -50},
    {type= 'None', x= 3072, y= -50},
    {type= 'None', x= 3168, y= -50},
    {type= 1, x= 3324, y= -50},


    {type= 2, x= 3360, y= -50},
    {type= 2, x= 3456, y= -50},
    {type= 2, x= 3552, y= -50},
    {type= 2, x= 3648, y= -50},
    {type= 2, x= 3744, y= -50},
    {type= 2, x= 3840, y= -50},
    {type= 2, x= 3936, y= -50},
    {type= 2, x= 4032, y= -50},
    {type= 2, x= 4128, y= -50},
    {type= 2, x= 4224, y= -50},
    {type= 2, x= 4320, y= -50},
    {type= 2, x= 4416, y= -50},
    {type= 2, x= 4512, y= -50},
    {type= 2, x= 4608, y= -50},
    {type= 2, x= 4704, y= -50},
    {type= 2, x= 4800, y= -50},
    {type= 2, x= 4896, y= -50},
    {type= 2, x= 4992, y= -50},
    {type= 5, x= 5147, y= 200},
    {type= 6, x= 5184, y= 200},
    {type= 6, x= 5280, y= 200},
    {type= 6, x= 5376, y= 200},
    {type= 6, x= 5472, y= 200},
    {type= 6, x= 5568, y= 200},
    {type= 7, x= 5664, y= 200},
    {type= 4, x= 5760, y= 180},
    {type= 4, x= 5856, y= 160},
    {type= 4, x= 5952, y= 140},
    {type= 4, x= 6048, y= 120},
    {type= 4, x= 6144, y= 100},
    {type= 2, x= 6240, y= -50},
    {type= 2, x= 6336, y= -50},
    {type= 2, x= 6432, y= -50},
    {type= 2, x= 6528, y= -50},
    {type= 2, x= 6624, y= -50},
    {type= 2, x= 6720, y= -50},
    {type= 2, x= 6816, y= -50},
    {type= 2, x= 6912, y= -50},
    {type= 2, x= 7008, y= -50},
    {type= 2, x= 7104, y= -50},
    {type= 2, x= 7200, y= -50},
    {type= 2, x= 7296, y= -50},
    {type= 2, x= 7392, y= -50},
    {type= 2, x= 7488, y= -50},
    {type= 2, x= 7584, y= -50},
    {type= 2, x= 7680, y= -50},
    {type= 2, x= 7776, y= -50},
    {type= 2, x= 7872, y= -50},
    {type= 2, x= 7968, y= -50},
    {type= 2, x= 8064, y= -50},
    {type= 2, x= 8160, y= -50},
    {type= 2, x= 8256, y= -50},
    {type= 2, x= 8352, y= -50},
    {type= 2, x= 8448, y= -50},
    {type= 2, x= 8544, y= -50},
    {type= 2, x= 8640, y= -50},
    {type= 2, x= 8736, y= -50},
    {type= 2, x= 8832, y= -50},
    {type= 2, x= 8928, y= -50},
    {type= 2, x= 9024, y= -50},
    {type= 2, x= 9120, y= -50},
    {type= 2, x= 9216, y= -50},
    {type= 2, x= 9312, y= -50},
    {type= 2, x= 9408, y= -50},
    {type= 2, x= 9504, y= -50},
    {type= 2, x= 9600, y= -50},
    {type= 2, x= 9696, y= -50},
    {type= 2, x= 9792, y= -50},
    {type= 2, x= 9888, y= -50},
    {type= 2, x= 9984, y= -50},
    {type= 2, x= 10080, y= -50},
    {type= 2, x= 10176, y= -50},
    {type= 2, x= 10272, y= -50},
    {type= 2, x= 10368, y= -50},
    {type= 2, x= 10464, y= -50},
    {type= 2, x= 10560, y= -50},
    {type= 2, x= 10656, y= -50},
    {type= 2, x= 10752, y= -50},
    {type= 2, x= 10848, y= -50},
    {type= 2, x= 10944, y= -50},
    {type= 2, x= 11040, y= -50},
    {type= 2, x= 11136, y= -50},
    {type= 2, x= 11232, y= -50},
    {type= 2, x= 11328, y= -50},
    {type= 2, x= 11424, y= -50},
    {type= 2, x= 11520, y= -50},
    {type= 2, x= 11616, y= -50},
    {type= 2, x= 11712, y= -50},
    {type= 2, x= 11808, y= -50},
    {type= 2, x= 11904, y= -50},
    {type= 2, x= 12000, y= -50},
    {type= 2, x= 12096, y= -50},
    {type= 2, x= 12192, y= -50},
    {type= 2, x= 12288, y= -50},
    {type= 2, x= 12384, y= -50},
    {type= 2, x= 12480, y= -50},
    {type= 2, x= 12576, y= -50},
    {type= 2, x= 12672, y= -50},
    {type= 2, x= 12768, y= -50},
    {type= 2, x= 12864, y= -50},
    {type= 2, x= 12960, y= -50},
    {type= 2, x= 13056, y= -50},
    {type= 2, x= 13152, y= -50},
    {type= 2, x= 13248, y= -50},
    {type= 2, x= 13344, y= -50},
    {type= 2, x= 13440, y= -50},
    {type= 2, x= 13536, y= -50},
    {type= 2, x= 13632, y= -50},
    {type= 2, x= 13728, y= -50},
    {type= 2, x= 13824, y= -50},
    {type= 2, x= 13920, y= -50},
    {type= 2, x= 14016, y= -50},
    {type= 2, x= 14112, y= -50},
    {type= 2, x= 14208, y= -50},
    {type= 2, x= 14304, y= -50},
    {type= 2, x= 14400, y= -50},
    {type= 2, x= 14496, y= -50},
    {type= 2, x= 14592, y= -50},
    {type= 2, x= 14688, y= -50},
    {type= 2, x= 14784, y= -50},
    {type= 2, x= 14880, y= -50},
    {type= 2, x= 14976, y= -50},
    {type= 2, x= 15072, y= -50},
    {type= 2, x= 15168, y= -50},
    {type= 2, x= 15264, y= -50},
    {type= 2, x= 15360, y= -50},
    {type= 2, x= 15456, y= -50},
    {type= 2, x= 15552, y= -50},
    {type= 2, x= 15648, y= -50},
    {type= 2, x= 15744, y= -50},
    {type= 2, x= 15840, y= -50},
    {type= 2, x= 15936, y= -50},
    {type= 2, x= 16032, y= -50},
    {type= 2, x= 16128, y= -50},
    {type= 2, x= 16224, y= -50},
    {type= 2, x= 16320, y= -50},
    {type= 2, x= 16416, y= -50},
    {type= 2, x= 16512, y= -50},
    {type= 2, x= 16608, y= -50},
    {type= 2, x= 16704, y= -50},
    {type= 2, x= 16800, y= -50},
    {type= 2, x= 16896, y= -50},
    {type= 2, x= 16992, y= -50},
    {type= 2, x= 17088, y= -50},
    {type= 2, x= 17184, y= -50},
    {type= 2, x= 17280, y= -50},
    {type= 2, x= 17376, y= -50},
    {type= 2, x= 17472, y= -50},
    {type= 2, x= 17568, y= -50},
    {type= 2, x= 17664, y= -50},
    {type= 2, x= 17760, y= -50},
    {type= 2, x= 17856, y= -50},
    {type= 2, x= 17952, y= -50},
    {type= 2, x= 18048, y= -50},
    {type= 2, x= 18144, y= -50},
    {type= 2, x= 18240, y= -50},
    {type= 2, x= 18336, y= -50},
    {type= 2, x= 18432, y= -50},
    {type= 2, x= 18528, y= -50},
    {type= 2, x= 18624, y= -50},
    {type= 2, x= 18720, y= -50},
    {type= 2, x= 18816, y= -50},
    {type= 2, x= 18912, y= -50},
    {type= 2, x= 19008, y= -50},
    {type= 2, x= 19104, y= -50},
    {type= 2, x= 19200, y= -50},
    {type= 2, x= 19296, y= -50},
    {type= 2, x= 19392, y= -50},
    {type= 2, x= 19488, y= -50},
    {type= 2, x= 19584, y= -50},
    {type= 2, x= 19680, y= -50},
    {type= 2, x= 19776, y= -50},
    {type= 2, x= 19872, y= -50},
    {type= 2, x= 19968, y= -50},
    {type= 2, x= 20064, y= -50},
    {type= 2, x= 20160, y= -50},
    {type= 2, x= 20256, y= -50},
    {type= 2, x= 20352, y= -50},
    {type= 2, x= 20448, y= -50},
    {type= 2, x= 20544, y= -50},
    {type= 2, x= 20640, y= -50},
    {type= 2, x= 20736, y= -50},
    {type= 2, x= 20832, y= -50},
    {type= 2, x= 20928, y= -50},
    {type= 2, x= 21024, y= -50},
    {type= 2, x= 21120, y= -50},
    {type= 2, x= 21216, y= -50},
    {type= 2, x= 21312, y= -50},
    {type= 2, x= 21408, y= -50},
    {type= 2, x= 21504, y= -50},
    {type= 2, x= 21600, y= -50},
    {type= 2, x= 21696, y= -50},
    {type= 2, x= 21792, y= -50},
    {type= 2, x= 21888, y= -50},
    {type= 2, x= 21984, y= -50},
    {type= 2, x= 22080, y= -50},
    {type= 2, x= 22176, y= -50},
    {type= 2, x= 22272, y= -50},
    {type= 2, x= 22368, y= -50},
    {type= 2, x= 22464, y= -50},
    {type= 2, x= 22560, y= -50},
    {type= 2, x= 22656, y= -50},
    {type= 2, x= 22752, y= -50},
    {type= 2, x= 22848, y= -50},
    {type= 2, x= 22944, y= -50},
    {type= 2, x= 23040, y= -50},
    {type= 2, x= 23136, y= -50},
    {type= 2, x= 23232, y= -50},
    {type= 2, x= 23328, y= -50},
    {type= 2, x= 23424, y= -50},
    {type= 2, x= 23520, y= -50},
    {type= 2, x= 23616, y= -50},
    {type= 2, x= 23712, y= -50},
    {type= 2, x= 23808, y= -50},
    {type= 2, x= 23904, y= -50},
    {type= 2, x= 24000, y= -50},
    {type= 2, x= 24096, y= -50},
    {type= 2, x= 24192, y= -50},
    {type= 2, x= 24288, y= -50},
    {type= 2, x= 24384, y= -50},
    {type= 2, x= 24480, y= -50},
    {type= 2, x= 24576, y= -50},
    {type= 2, x= 24672, y= -50},
    {type= 2, x= 24768, y= -50},
    {type= 2, x= 24864, y= -50},
    {type= 2, x= 24960, y= -50},
    {type= 2, x= 25056, y= -50},
    {type= 2, x= 25152, y= -50},
    {type= 2, x= 25248, y= -50},
    {type= 2, x= 25344, y= -50},
    {type= 2, x= 25440, y= -50},
    {type= 2, x= 25536, y= -50},
    {type= 2, x= 25632, y= -50},
    {type= 2, x= 25728, y= -50},
    {type= 2, x= 25824, y= -50},
    {type= 2, x= 25920, y= -50},
    {type= 2, x= 26016, y= -50},
    {type= 2, x= 26112, y= -50},
    {type= 2, x= 26208, y= -50},
    {type= 2, x= 26304, y= -50},
    {type= 2, x= 26400, y= -50},
    {type= 2, x= 26496, y= -50},
    {type= 2, x= 26592, y= -50},
    {type= 2, x= 26688, y= -50},
    {type= 2, x= 26784, y= -50},
    {type= 2, x= 26880, y= -50},
    {type= 2, x= 26976, y= -50},
    {type= 2, x= 27072, y= -50},
    {type= 2, x= 27168, y= -50},
    {type= 2, x= 27264, y= -50},
    {type= 2, x= 27360, y= -50},
    {type= 2, x= 27456, y= -50},
    {type= 2, x= 27552, y= -50},
    {type= 2, x= 27648, y= -50},
    {type= 2, x= 27744, y= -50},
    {type= 2, x= 27840, y= -50},
    {type= 2, x= 27936, y= -50},
    {type= 2, x= 28032, y= -50},
    {type= 2, x= 28128, y= -50},
    {type= 2, x= 28224, y= -50},
    {type= 2, x= 28320, y= -50},
    {type= 2, x= 28416, y= -50},
    {type= 2, x= 28512, y= -50},
    {type= 2, x= 28608, y= -50},
    {type= 2, x= 28704, y= -50},
    {type= 2, x= 28800, y= -50},
    {type= 2, x= 28896, y= -50},
    {type= 2, x= 28992, y= -50},
    {type= 2, x= 29088, y= -50},
    {type= 2, x= 29184, y= -50},
    {type= 2, x= 29280, y= -50},
    {type= 2, x= 29376, y= -50},
    {type= 2, x= 29472, y= -50},
    {type= 2, x= 29568, y= -50},
    {type= 2, x= 29664, y= -50},
    {type= 2, x= 29760, y= -50},
    {type= 2, x= 29856, y= -50},
    {type= 2, x= 29952, y= -50},
    {type= 2, x= 30048, y= -50},
    {type= 2, x= 30144, y= -50},
    {type= 2, x= 30240, y= -50},
    {type= 2, x= 30336, y= -50},
    {type= 2, x= 30432, y= -50},
    {type= 2, x= 30528, y= -50},
    {type= 2, x= 30624, y= -50},
    {type= 2, x= 30720, y= -50},
    {type= 2, x= 30816, y= -50},
    {type= 2, x= 30912, y= -50},
    {type= 2, x= 31008, y= -50},
    {type= 2, x= 31104, y= -50},
    {type= 2, x= 31200, y= -50},
    {type= 2, x= 31296, y= -50},
    {type= 2, x= 31392, y= -50},
    {type= 2, x= 31488, y= -50},
    {type= 2, x= 31584, y= -50},
    {type= 2, x= 31680, y= -50},
    {type= 2, x= 31776, y= -50},
    {type= 2, x= 31872, y= -50},
    {type= 2, x= 31968, y= -50},
    {type= 2, x= 32064, y= -50},
    {type= 2, x= 32160, y= -50},
    {type= 2, x= 32256, y= -50},
    {type= 2, x= 32352, y= -50},
    {type= 2, x= 32448, y= -50},
    {type= 2, x= 32544, y= -50},
    {type= 2, x= 32640, y= -50},
    {type= 2, x= 32736, y= -50},
    {type= 2, x= 32832, y= -50},
    {type= 2, x= 32928, y= -50},
    {type= 2, x= 33024, y= -50},
    {type= 2, x= 33120, y= -50},
    {type= 2, x= 33216, y= -50},
    {type= 2, x= 33312, y= -50},
    {type= 2, x= 33408, y= -50},
    {type= 2, x= 33504, y= -50},
    {type= 2, x= 33600, y= -50},
    {type= 2, x= 33696, y= -50},
    {type= 2, x= 33792, y= -50},
    {type= 2, x= 33888, y= -50},
    {type= 2, x= 33984, y= -50},
    {type= 2, x= 34080, y= -50},
    {type= 2, x= 34176, y= -50},
    {type= 2, x= 34272, y= -50},
    {type= 2, x= 34368, y= -50},
    {type= 2, x= 34464, y= -50},
    {type= 2, x= 34560, y= -50},
    {type= 2, x= 34656, y= -50},
    {type= 2, x= 34752, y= -50},
    {type= 2, x= 34848, y= -50},
    {type= 2, x= 34944, y= -50},
    {type= 2, x= 35040, y= -50},
    {type= 2, x= 35136, y= -50},
    {type= 2, x= 35232, y= -50},
    {type= 2, x= 35328, y= -50},
    {type= 2, x= 35424, y= -50},
    {type= 2, x= 35520, y= -50},
    {type= 2, x= 35616, y= -50},
    {type= 2, x= 35712, y= -50},
    {type= 2, x= 35808, y= -50},
    {type= 2, x= 35904, y= -50},
    {type= 2, x= 36000, y= -50},
    {type= 2, x= 36096, y= -50},
    {type= 2, x= 36192, y= -50},
    {type= 2, x= 36288, y= -50},
    {type= 2, x= 36384, y= -50},
    {type= 2, x= 36480, y= -50},
    {type= 2, x= 36576, y= -50},
    {type= 2, x= 36672, y= -50},
    {type= 2, x= 36768, y= -50},
    {type= 2, x= 36864, y= -50},
    {type= 2, x= 36960, y= -50},
    {type= 2, x= 37056, y= -50},
    {type= 2, x= 37152, y= -50},
    {type= 2, x= 37248, y= -50},
    {type= 2, x= 37344, y= -50},
    {type= 2, x= 37440, y= -50},
    {type= 2, x= 37536, y= -50},
    {type= 2, x= 37632, y= -50},
    {type= 2, x= 37728, y= -50},
    {type= 2, x= 37824, y= -50},
    {type= 2, x= 37920, y= -50},
    {type= 2, x= 38016, y= -50},
    {type= 2, x= 38112, y= -50},
    {type= 2, x= 38208, y= -50},
    {type= 2, x= 38304, y= -50},
    {type= 2, x= 38400, y= -50},
    {type= 2, x= 38496, y= -50},
    {type= 2, x= 38592, y= -50},
    {type= 2, x= 38688, y= -50},
    {type= 2, x= 38784, y= -50},
    {type= 2, x= 38880, y= -50},
    {type= 2, x= 38976, y= -50},
    {type= 2, x= 39072, y= -50},
    {type= 2, x= 39168, y= -50},
    {type= 2, x= 39264, y= -50},
    {type= 2, x= 39360, y= -50},
    {type= 2, x= 39456, y= -50},
    {type= 2, x= 39552, y= -50},
    {type= 2, x= 39648, y= -50},
    {type= 2, x= 39744, y= -50},
    {type= 2, x= 39840, y= -50},
    {type= 2, x= 39936, y= -50},
    {type= 2, x= 40032, y= -50},
    {type= 2, x= 40128, y= -50},
    {type= 2, x= 40224, y= -50},
    {type= 2, x= 40320, y= -50},
    {type= 2, x= 40416, y= -50},
    {type= 2, x= 40512, y= -50},
    {type= 2, x= 40608, y= -50},
    {type= 2, x= 40704, y= -50},
    {type= 2, x= 40800, y= -50},
    {type= 2, x= 40896, y= -50},
    {type= 2, x= 40992, y= -50},
    {type= 2, x= 41088, y= -50},
    {type= 2, x= 41184, y= -50},
    {type= 2, x= 41280, y= -50},
    {type= 2, x= 41376, y= -50},
    {type= 2, x= 41472, y= -50},
    {type= 2, x= 41568, y= -50},
    {type= 2, x= 41664, y= -50},
    {type= 2, x= 41760, y= -50},
    {type= 2, x= 41856, y= -50},
    {type= 2, x= 41952, y= -50},
    {type= 2, x= 42048, y= -50},
    {type= 2, x= 42144, y= -50},
    {type= 2, x= 42240, y= -50},
    {type= 2, x= 42336, y= -50},
    {type= 2, x= 42432, y= -50},
    {type= 2, x= 42528, y= -50},
    {type= 2, x= 42624, y= -50},
    {type= 2, x= 42720, y= -50},
    {type= 2, x= 42816, y= -50},
    {type= 2, x= 42912, y= -50},
    {type= 2, x= 43008, y= -50},
    {type= 2, x= 43104, y= -50},
    {type= 2, x= 43200, y= -50},
    {type= 2, x= 43296, y= -50},
    {type= 2, x= 43392, y= -50},
    {type= 2, x= 43488, y= -50},
    {type= 2, x= 43584, y= -50},
    {type= 2, x= 43680, y= -50},
    {type= 2, x= 43776, y= -50},
    {type= 2, x= 43872, y= -50},
    {type= 2, x= 43968, y= -50},
    {type= 2, x= 44064, y= -50},
    {type= 2, x= 44160, y= -50},
    {type= 2, x= 44256, y= -50},
    {type= 2, x= 44352, y= -50},
    {type= 2, x= 44448, y= -50},
    {type= 2, x= 44544, y= -50},
    {type= 2, x= 44640, y= -50},
    {type= 2, x= 44736, y= -50},
    {type= 2, x= 44832, y= -50},
    {type= 2, x= 44928, y= -50},
    {type= 2, x= 45024, y= -50},
    {type= 2, x= 45120, y= -50},
    {type= 2, x= 45216, y= -50},
    {type= 2, x= 45312, y= -50},
    {type= 2, x= 45408, y= -50},
    {type= 2, x= 45504, y= -50},
    {type= 2, x= 45600, y= -50},
    {type= 2, x= 45696, y= -50},
    {type= 2, x= 45792, y= -50},
    {type= 2, x= 45888, y= -50},
    {type= 2, x= 45984, y= -50},
    {type= 2, x= 46080, y= -50},
    {type= 2, x= 46176, y= -50},
    {type= 2, x= 46272, y= -50},
    {type= 2, x= 46368, y= -50},
    {type= 2, x= 46464, y= -50},
    {type= 2, x= 46560, y= -50},
    {type= 2, x= 46656, y= -50},
    {type= 2, x= 46752, y= -50},
    {type= 2, x= 46848, y= -50},
    {type= 2, x= 46944, y= -50},
    {type= 2, x= 47040, y= -50},
    {type= 2, x= 47136, y= -50},
    {type= 2, x= 47232, y= -50},
    {type= 2, x= 47328, y= -50},
    {type= 2, x= 47424, y= -50},
    {type= 2, x= 47520, y= -50},
    {type= 2, x= 47616, y= -50},
    {type= 2, x= 47712, y= -50},
    {type= 2, x= 47808, y= -50},
    {type= 2, x= 47904, y= -50},

]